// <auto-generated />
using System;
using CRM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Infrastructure.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Core.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("DealId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Created deal: TechVision Cloud Migration",
                            EntityId = 1,
                            EntityType = "Deal",
                            Type = "Created",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 1, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Deal moved to Proposal stage",
                            EntityId = 1,
                            EntityType = "Deal",
                            Type = "DealStageChanged",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ContactId = 1,
                            CreatedAt = new DateTime(2024, 3, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Called James Wilson about project timeline",
                            EntityId = 1,
                            EntityType = "Contact",
                            Type = "Call",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            ContactId = 2,
                            CreatedAt = new DateTime(2024, 3, 18, 11, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Sent pricing proposal to Lisa Anderson",
                            EntityId = 2,
                            EntityType = "Contact",
                            Type = "Email",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 2, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Created deal: HealthFirst Telemedicine Platform",
                            EntityId = 3,
                            EntityType = "Deal",
                            Type = "Created",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            ContactId = 3,
                            CreatedAt = new DateTime(2024, 3, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Meeting with Robert Martinez - product demo",
                            EntityId = 3,
                            EntityType = "Contact",
                            Type = "Meeting",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            ContactId = 4,
                            CreatedAt = new DateTime(2024, 3, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Amanda interested in solar panels for new office",
                            EntityId = 4,
                            EntityType = "Contact",
                            Type = "Note",
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 4, 15, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "FinanceFlow Payment Gateway moved to Closed Won",
                            EntityId = 5,
                            EntityType = "Deal",
                            Type = "DealStageChanged",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            ContactId = 8,
                            CreatedAt = new DateTime(2024, 3, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New contact added: Michelle Garcia",
                            EntityId = 8,
                            EntityType = "Contact",
                            Type = "Created",
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 3, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Updated company info for Global Dynamics",
                            EntityId = 2,
                            EntityType = "Company",
                            Type = "Updated",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CRM.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AnnualRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 Innovation Blvd",
                            AnnualRevenue = 50000000m,
                            City = "San Francisco",
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Leading AI and cloud solutions provider",
                            Email = "info@techvision.com",
                            Industry = "Technology",
                            Name = "TechVision Inc.",
                            Phone = "+1-555-1001",
                            Size = "201-500",
                            Website = "https://techvision.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "500 Industrial Way",
                            AnnualRevenue = 120000000m,
                            City = "Detroit",
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced manufacturing and robotics",
                            Email = "contact@globaldynamics.com",
                            Industry = "Manufacturing",
                            Name = "Global Dynamics",
                            Phone = "+1-555-1002",
                            Size = "500+",
                            Website = "https://globaldynamics.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "200 Medical Center Dr",
                            AnnualRevenue = 25000000m,
                            City = "Boston",
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Digital health and telemedicine solutions",
                            Email = "info@healthfirst.com",
                            Industry = "Healthcare",
                            Name = "HealthFirst Medical",
                            Phone = "+1-555-1003",
                            Size = "51-200",
                            Website = "https://healthfirst.com"
                        },
                        new
                        {
                            Id = 4,
                            Address = "75 Green Energy Rd",
                            AnnualRevenue = 8000000m,
                            City = "Austin",
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Renewable energy consulting and implementation",
                            Email = "hello@ecosmart.com",
                            Industry = "Energy",
                            Name = "EcoSmart Solutions",
                            Phone = "+1-555-1004",
                            Size = "11-50",
                            Website = "https://ecosmart.com"
                        },
                        new
                        {
                            Id = 5,
                            Address = "300 Wall St",
                            AnnualRevenue = 75000000m,
                            City = "New York",
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Financial technology and payment processing",
                            Email = "support@financeflow.com",
                            Industry = "Finance",
                            Name = "FinanceFlow Corp",
                            Phone = "+1-555-1005",
                            Size = "201-500",
                            Website = "https://financeflow.com"
                        });
                });

            modelBuilder.Entity("CRM.Core.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastContactedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "San Francisco",
                            CompanyId = 1,
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james@techvision.com",
                            FirstName = "James",
                            JobTitle = "CTO",
                            LastName = "Wilson",
                            OwnerId = 2,
                            Phone = "+1-555-2001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            City = "Detroit",
                            CompanyId = 2,
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lisa@globaldynamics.com",
                            FirstName = "Lisa",
                            JobTitle = "VP of Operations",
                            LastName = "Anderson",
                            OwnerId = 2,
                            Phone = "+1-555-2002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            City = "Boston",
                            CompanyId = 3,
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "robert@healthfirst.com",
                            FirstName = "Robert",
                            JobTitle = "CEO",
                            LastName = "Martinez",
                            OwnerId = 3,
                            Phone = "+1-555-2003",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            City = "Austin",
                            CompanyId = 4,
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amanda@ecosmart.com",
                            FirstName = "Amanda",
                            JobTitle = "Head of Procurement",
                            LastName = "Thompson",
                            OwnerId = 3,
                            Phone = "+1-555-2004",
                            Status = "Lead"
                        },
                        new
                        {
                            Id = 5,
                            City = "New York",
                            CompanyId = 5,
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david@financeflow.com",
                            FirstName = "David",
                            JobTitle = "CFO",
                            LastName = "Kim",
                            OwnerId = 2,
                            Phone = "+1-555-2005",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            City = "San Francisco",
                            CompanyId = 1,
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jennifer@techvision.com",
                            FirstName = "Jennifer",
                            JobTitle = "Product Manager",
                            LastName = "Brown",
                            OwnerId = 4,
                            Phone = "+1-555-2006",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            City = "Detroit",
                            CompanyId = 2,
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "chris@globaldynamics.com",
                            FirstName = "Chris",
                            JobTitle = "Engineering Lead",
                            LastName = "Taylor",
                            OwnerId = 3,
                            Phone = "+1-555-2007",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 8,
                            City = "Los Angeles",
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "michelle@gmail.com",
                            FirstName = "Michelle",
                            JobTitle = "Freelance Consultant",
                            LastName = "Garcia",
                            OwnerId = 4,
                            Phone = "+1-555-2008",
                            Status = "Lead"
                        });
                });

            modelBuilder.Entity("CRM.Core.Entities.CrmTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Todo");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ContactId");

                    b.HasIndex("DealId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssigneeId = 2,
                            ContactId = 1,
                            CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealId = 1,
                            Description = "Discuss cloud migration requirements",
                            DueDate = new DateTime(2026, 9, 28, 16, 25, 4, 899, DateTimeKind.Utc).AddTicks(5504),
                            Priority = "High",
                            Status = "Todo",
                            Title = "Follow up with James Wilson",
                            Type = "Call"
                        },
                        new
                        {
                            Id = 2,
                            AssigneeId = 2,
                            ContactId = 2,
                            CreatedAt = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealId = 2,
                            Description = "ERP system proposal document",
                            DueDate = new DateTime(2026, 9, 29, 16, 25, 4, 899, DateTimeKind.Utc).AddTicks(7218),
                            Priority = "High",
                            Status = "InProgress",
                            Title = "Send proposal to Global Dynamics",
                            Type = "Email"
                        },
                        new
                        {
                            Id = 3,
                            AssigneeId = 3,
                            ContactId = 3,
                            CreatedAt = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealId = 3,
                            Description = "Telemedicine platform demonstration",
                            DueDate = new DateTime(2026, 10, 2, 16, 25, 4, 899, DateTimeKind.Utc).AddTicks(7229),
                            Priority = "Medium",
                            Status = "Todo",
                            Title = "Schedule demo for HealthFirst",
                            Type = "Meeting"
                        },
                        new
                        {
                            Id = 4,
                            AssigneeId = 3,
                            CompletedAt = new DateTime(2026, 9, 26, 16, 25, 4, 899, DateTimeKind.Utc).AddTicks(7233),
                            ContactId = 4,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealId = 4,
                            Description = "Competitive analysis for solar proposal",
                            DueDate = new DateTime(2026, 9, 25, 16, 25, 4, 899, DateTimeKind.Utc).AddTicks(7232),
                            Priority = "Low",
                            Status = "Completed",
                            Title = "Research EcoSmart competitors",
                            Type = "Task"
                        },
                        new
                        {
                            Id = 5,
                            AssigneeId = 2,
                            ContactId = 5,
                            CreatedAt = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealId = 9,
                            Description = "Legal review of payment gateway contract",
                            DueDate = new DateTime(2026, 9, 27, 16, 25, 4, 899, DateTimeKind.Utc).AddTicks(8036),
                            Priority = "Urgent",
                            Status = "Todo",
                            Title = "Review FinanceFlow contract",
                            Type = "Task"
                        },
                        new
                        {
                            Id = 6,
                            AssigneeId = 4,
                            CreatedAt = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ensure all Q1 deals and contacts are up to date",
                            DueDate = new DateTime(2026, 10, 4, 16, 25, 4, 899, DateTimeKind.Utc).AddTicks(8039),
                            Priority = "Medium",
                            Status = "Todo",
                            Title = "Update CRM data for Q1",
                            Type = "Task"
                        });
                });

            modelBuilder.Entity("CRM.Core.Entities.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Probability")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Lead");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            ContactId = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 2,
                            Priority = "High",
                            Probability = 60,
                            Stage = "Proposal",
                            Title = "TechVision Cloud Migration",
                            Value = 150000m
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            ContactId = 2,
                            CreatedAt = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 2,
                            Priority = "High",
                            Probability = 75,
                            Stage = "Negotiation",
                            Title = "Global Dynamics ERP System",
                            Value = 320000m
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            ContactId = 3,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 3,
                            Priority = "Medium",
                            Probability = 40,
                            Stage = "Qualified",
                            Title = "HealthFirst Telemedicine Platform",
                            Value = 85000m
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 4,
                            ContactId = 4,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 3,
                            Priority = "Low",
                            Probability = 20,
                            Stage = "Lead",
                            Title = "EcoSmart Solar Installation",
                            Value = 45000m
                        },
                        new
                        {
                            Id = 5,
                            ActualCloseDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 5,
                            ContactId = 5,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 2,
                            Priority = "High",
                            Probability = 100,
                            Stage = "Closed Won",
                            Title = "FinanceFlow Payment Gateway",
                            Value = 200000m
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 1,
                            ContactId = 6,
                            CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 4,
                            Priority = "Medium",
                            Probability = 15,
                            Stage = "Lead",
                            Title = "TechVision AI Analytics",
                            Value = 95000m
                        },
                        new
                        {
                            Id = 7,
                            ActualCloseDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 2,
                            ContactId = 2,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 2,
                            Priority = "High",
                            Probability = 100,
                            Stage = "Closed Won",
                            Title = "Global Dynamics Automation",
                            Value = 175000m
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 3,
                            ContactId = 3,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 3,
                            Priority = "Medium",
                            Probability = 50,
                            Stage = "Proposal",
                            Title = "HealthFirst Data Analytics",
                            Value = 62000m
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 5,
                            ContactId = 5,
                            CreatedAt = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 2,
                            Priority = "High",
                            Probability = 35,
                            Stage = "Qualified",
                            Title = "FinanceFlow Fraud Detection",
                            Value = 280000m
                        },
                        new
                        {
                            Id = 10,
                            ActualCloseDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 4,
                            ContactId = 4,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCloseDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 4,
                            Priority = "Low",
                            Probability = 0,
                            Stage = "Closed Lost",
                            Title = "EcoSmart Consulting",
                            Value = 30000m
                        });
                });

            modelBuilder.Entity("CRM.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Management",
                            Email = "admin@crm.com",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "$2a$11$rZbKpBqLDmJPhGQ5DaTK4OZGo5bLwHxHlU9xG2WcPAZpxHGKzLxCu",
                            Phone = "+1-555-0100",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Sales",
                            Email = "sarah@crm.com",
                            FullName = "Sarah Johnson",
                            IsActive = true,
                            PasswordHash = "$2a$11$rZbKpBqLDmJPhGQ5DaTK4OZGo5bLwHxHlU9xG2WcPAZpxHGKzLxCu",
                            Phone = "+1-555-0101",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Sales",
                            Email = "michael@crm.com",
                            FullName = "Michael Chen",
                            IsActive = true,
                            PasswordHash = "$2a$11$rZbKpBqLDmJPhGQ5DaTK4OZGo5bLwHxHlU9xG2WcPAZpxHGKzLxCu",
                            Phone = "+1-555-0102",
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Email = "emily@crm.com",
                            FullName = "Emily Davis",
                            IsActive = true,
                            PasswordHash = "$2a$11$rZbKpBqLDmJPhGQ5DaTK4OZGo5bLwHxHlU9xG2WcPAZpxHGKzLxCu",
                            Phone = "+1-555-0103",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("CRM.Core.Entities.Activity", b =>
                {
                    b.HasOne("CRM.Core.Entities.Contact", "Contact")
                        .WithMany("Activities")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Core.Entities.Deal", null)
                        .WithMany("Activities")
                        .HasForeignKey("DealId");

                    b.HasOne("CRM.Core.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CRM.Core.Entities.Contact", b =>
                {
                    b.HasOne("CRM.Core.Entities.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Core.Entities.User", "Owner")
                        .WithMany("OwnedContacts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CRM.Core.Entities.CrmTask", b =>
                {
                    b.HasOne("CRM.Core.Entities.User", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM.Core.Entities.Contact", "Contact")
                        .WithMany("Tasks")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Core.Entities.Deal", "Deal")
                        .WithMany("Tasks")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignee");

                    b.Navigation("Contact");

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("CRM.Core.Entities.Deal", b =>
                {
                    b.HasOne("CRM.Core.Entities.Company", "Company")
                        .WithMany("Deals")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Core.Entities.Contact", "Contact")
                        .WithMany("Deals")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM.Core.Entities.User", "Owner")
                        .WithMany("OwnedDeals")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CRM.Core.Entities.Company", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Deals");
                });

            modelBuilder.Entity("CRM.Core.Entities.Contact", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Deals");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CRM.Core.Entities.Deal", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CRM.Core.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("AssignedTasks");

                    b.Navigation("OwnedContacts");

                    b.Navigation("OwnedDeals");
                });
#pragma warning restore 612, 618
        }
    }
}
